language: java
sudo: false # faster builds

jdk:
  - oraclejdk8
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - travis_wait 30 ./mvnw -T 1C clean install -DskipTests=true -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - if [ -f logs/tddl/tddl.log ]; then echo "------TAIL of tddl.log------"; tail -n 1000 logs/tddl/tddl.log; echo "------END of tddl.log------"; fi
