name: ci

on:
  pull_request:
    branches: 
      - master
      - tags/*

   push:
    branches:
      - master
      - tags/*

env:
  MAVEN_CUSTOM_OPTS: "-Xmx4g -XX:+ExitOnOutOfMemoryError"
  RETRY: .github/bin/retry

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    timeout-minutes: 60
    steps:
      - name: Free Disk Space
        run: |
          df -h
          sudo apt-get clean
          df -h
      - uses: actions/checkout@v2
      - name: submodule init
        run: |
          git submodule init && git submodule update
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache local Maven repository
        id: cache-maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-2-
      - name: Populate maven cache
        if: steps.cache-maven.outputs.cache-hit != 'true'
        run: ./mvnw de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
      - name: Maven Build
        run: |
          export MAVEN_OPTS="${MAVEN_CUSTOM_OPTS}"
          ./mvnw -T 1C clean package install -DskipTests -Dcheckstyle.skip=true -Dmaven.javadoc.skip=true